version: '3.8'
services:
  web:
    build:
      context: ./SnipEx
      dockerfile: SnipEx.Web/Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${WEB_CONNECTION_STRING}
    depends_on:
      - db

  api:
    build:
      context: ./SnipEx
      dockerfile: SnipEx.WebApi/Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${API_CONNECTION_STRING}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - api

volumes:
  sql_data:
